-- Migration: Sprint 1 — Order Management Foundation
-- Changes:
--   1. Order.status → OrderStatus enum
--   2. Add shipping/delivery fields to Order
--   3. Create TrackingEvent model
--   4. Add name, status, autoGenerated to Coupon

-- Step 1: Create enum if not exists (for Order.status)
DO $$ BEGIN
  CREATE TYPE "OrderStatus" AS ENUM ('PENDING_PAYMENT', 'PAID', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- Step 2: Alter Order.status to use the enum
-- First add a temp column, copy data, drop old, rename
ALTER TABLE "orders" ADD COLUMN "status_new" "OrderStatus" NOT NULL DEFAULT 'PENDING_PAYMENT';
UPDATE "orders" SET "status_new" = UPPER(TRIM("status"))::"OrderStatus";
ALTER TABLE "orders" DROP COLUMN "status";
ALTER TABLE "orders" RENAME COLUMN "status_new" TO "status";

-- Step 3: Add new columns to orders table
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "shipped_at" TIMESTAMPTZ;
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "delivered_at" TIMESTAMPTZ;
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "estimated_delivery" TIMESTAMPTZ;
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "delivery_status" TEXT;
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "tracking_number" TEXT;
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "shipping_company" TEXT;

-- Step 4: Create TrackingEvent table
CREATE TABLE IF NOT EXISTS "tracking_events" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "order_id" UUID NOT NULL REFERENCES "orders"("id") ON DELETE CASCADE,
  "status" TEXT NOT NULL,
  "location" TEXT,
  "description" TEXT,
  "tracking_number" TEXT,
  "shipping_company" TEXT,
  "timestamp" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "tracking_events_order_id_timestamp_idx" ON "tracking_events"("order_id", "timestamp");

-- Step 5: Add coupon fields
ALTER TABLE "coupons" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "coupons" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE "coupons" ADD COLUMN IF NOT EXISTS "auto_generated" BOOLEAN NOT NULL DEFAULT false;
CREATE INDEX IF NOT EXISTS "coupons_is_active_status_expires_at_idx" ON "coupons"("is_active", "status", "expires_at");

-- Step 6: Add discount fields to existing orders if missing
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "coupon_id" TEXT;
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "coupon_code" TEXT;
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "discount_amount" DECIMAL(10,2);
